---
- name: Install iptables-persistent
  apt: name=iptables-persistent state=present

- name: Flush all rules
  iptables: flush=yes

- name: Allow related inbound
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT

- name: Allow localhost REDIS
  iptables: chain=INPUT source=localhost protocol=tcp destination_port=6379 jump=ACCEPT

- name: Allow LDAP
  iptables: chain=INPUT source=localhost protocol=tcp destination_port=389 jump=ACCEPT
  when: type == "ldap"

- name: Allow SSH
  iptables: chain=INPUT protocol=tcp destination_port=22 jump=ACCEPT

- name: Allow HTTP
  iptables: chain=INPUT protocol=tcp destination_port=80 jump=ACCEPT

- name: Allow HTTPS
  iptables: chain=INPUT protocol=tcp destination_port=443 jump=ACCEPT

- name: Allow HTTPS (444 for receiver)
  iptables: chain=INPUT protocol=tcp destination_port=444 jump=ACCEPT

- name: Block all incoming
  iptables: chain=INPUT jump=DROP

- name: Save iptables rules
  command: netfilter-persistent save

