---
  directory:
    dn: DC=michael,DC=hippo,DC=local
    fqdn: michael.hippo.local

  frontend:
    address: http://127.0.0.1:5002

  auth_service:
    address: http://127.0.0.1:5000 #https://gas.nis1.national.ncrs.nhs.uk
    #http://10.211.55.2:5000

#  directory:
#    dn: OU=Departments,DC=xRothGen,DC=nhs,DC=uk
#    fqdn: xRothGen.nhs.uk
#
#  frontend:
#    address: https://pwd.hippo.digital:444

  sms:
    message: "A reset code has been requested for your account.\n\nIf this was in error contact the service desk on extension 8844.\n\nYour reset code is %s"
    organisation_shortname: "441466455031"
    twilio_sid: <twilio_sid>
    twilio_authcode: <twilio_authcode>

  redis:
    address: 127.0.0.1
    port: 6379
    db: 0


  private_key: >
    <private key>
